apiVersion: v1
kind: Template
metadata:
  name: '${APP_NAME}'
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: '${APP_NAME}'
      namespace: ${NAMESPACE}
      labels:
        app: '${APP_NAME}'
    spec:
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
        resources: {}
        activeDeadlineSeconds: 21600
      triggers:
        - type: ConfigChange
      replicas: 1
      revisionHistoryLimit: 5
      test: false
      selector:
        app: '${APP_NAME}'
        deploymentconfig: '${APP_NAME}'
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: '${APP_NAME}'
            deploymentconfig: '${APP_NAME}'
        spec:
          containers:
            - resources:
                limits:
                  cpu: '1'
                  memory: 2Gi
                requests:
                  cpu: 50m
                  memory: 512Mi
              terminationMessagePath: /dev/termination-log
              name: '${APP_NAME}'
              ports:
                - containerPort: 6021
                  protocol: TCP
              imagePullPolicy: IfNotPresent
              terminationMessagePolicy: File
              image: '${REGISTRY_URL}'
              env:
                - name: ConnectionStrings__DArchPostgreContext
                  valueFrom:
                    secretKeyRef:
                        name: '${SECRETPREFIXENV}-connectionstrings-secrets'
                        key: DArchPostgreContext
                - name: EuroMessageConfiguration__UserName
                  valueFrom:
                    secretKeyRef:
                        name: '${SECRETPREFIXENV}-euromessage-configuration-secrets'
                        key: UserName
                - name: EuroMessageConfiguration__Password
                  valueFrom:
                    secretKeyRef:
                        name: '${SECRETPREFIXENV}-euromessage-configuration-secrets'
                        key: Password
                - name: SmsConfiguration__User
                  valueFrom:
                    secretKeyRef:
                        name: '${SECRETPREFIXENV}-smsconfiguration-secrets'
                        key: User
                - name: SmsConfiguration__Password
                  valueFrom:
                    secretKeyRef:
                        name: '${SECRETPREFIXENV}-smsconfiguration-secrets'
                        key: Password
                - name: Kaltura__Secret
                  valueFrom:
                    secretKeyRef:
                        name: '${SECRETPREFIXENV}-kaltura-secrets'
                        key: Secret
                - name: CaptchaOptions__SecretKey
                  valueFrom:
                    secretKeyRef:
                        name: '${SECRETPREFIXENV}-captcha-options-secrets'
                        key: SecretKey                        
                - name: LdapConfig__adminUser
                  valueFrom:
                    secretKeyRef:
                        name: '${SECRETPREFIXENV}-ldap-config-secrets'
                        key: adminUser
                - name: LdapConfig__adminPass
                  valueFrom:
                    secretKeyRef:
                        name: '${SECRETPREFIXENV}-ldap-config-secrets'
                        key: adminPass
                - name: CapConfig__UserName
                  valueFrom:
                    secretKeyRef:
                        name: '${SECRETPREFIXENV}-cap-config-secrets'
                        key: UserName
                - name: CapConfig__Password
                  valueFrom:
                    secretKeyRef:
                        name: '${SECRETPREFIXENV}-cap-config-secrets'
                        key: Password
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
parameters:
  - name: REGISTRY_URL
    displayName: OpenShift Container Registry
    description: URL of the container in Registry (baseUrl/container-name:version)
    required: true
  - name: APP_NAME
    displayName: Application Name
    description: Unique application name
    required: true 
  - name: NAMESPACE
    displayName: Service Name
    description: Unique service name
    required: true
  - name: SECRETPREFIXENV
    displayName: Secret Prefix
    description: Secret Prefix
    required: true    